### ISSUE TITLE
/reboot : Not Working

### ISSUE THREAD

**Issue by tomiprs0x** [MoveAngel/UserIndoBot#4]
After We moved to docker , Reboot Not working ,
Maybe gitpull to not working fine

**Comment by MrMissx** [comment]
> After We moved to docker , Reboot Not working ,
> Maybe gitpull to not working fine

For the reboot command change the default executable on Dockerfile to
```
# Run
CMD ["bash", "start"]
```

And for starting the container just use ```docker run --restart always [IMAGE]``` .
Then docker will automatically restart every time it stopped by /reboot

**Comment by tomiprs0x** [comment]
Why you just think? 
You Have fully acces r8?

**Comment by tomiprs0x** [comment]
Solved

https://github.com/MoveAngel/UserIndoBot/commit/770646ce8e019c33aee8fe744e333329f61b9a88
